# Knative Serving
apiVersion: serving.knative.dev/v1
kind: Service
metadata: 
  name: insane-knative-serving
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: knative-hello-world-go:1.0.0
          env: 
            - name: TARGET
              value: "EFS hello world knative"